### ISSUE TITLE
Swipeable prevents vertical scrolling even when onSwipeUp or onSwipeDown are not set.

### ISSUE THREAD

**Issue by tsantef** [phil303/react-touch#1]
I have a Swipeable object that should only detect left right swipes but should still allow default vertical scrolling. Swipeable objects seem to grab and prevent vertical scroll behavior even when no swipe up or down handler is specified.

```
<Swipeable onSwipeRight={this.back} onSwipeLeft={this.next} >
```

The above Swipeable does not allow the browser window to scroll vertically.

**Comment by phil303** [comment]
Ack, a couple versions back I removed any `preventDefaults` to address a similar issue to this but maybe something else is going on. I'll investigate tonight.

**Comment by phil303** [comment]
@tsantef I've tested this locally (Chrome/Safari on iOS and desktop) and I can't seem to duplicate it - vertical scroll behavior is maintained. Can you give me some more details? Are you sure you're not calling `preventDefault` somewhere? What version of the library are you using?

**Comment by tsantef** [comment]
I was on an older version 0.2.2. Seems to be working for me just fine now. Should have checked that first, sorry for the bother.
